import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React from 'react';
// import '@/app/globals.css'
import Navbar from '@/components/navbar/Navbar';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'DASHBOARD | PROMPTED',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen`}>
        <Navbar />
        <div className="flex justify-between" style={{ height: "calc(100vh - 92px)" }}>
          <div className="size-full h-full overflow-auto">

            {children}
          </div>
        </div>
      </body>
    </html>
  );
}

