import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React from 'react';
import './globals.css';
import "@/styles/prism.css"
import { ThemeProvider } from "@/components/theme/ThemeProvider";
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'PROMPTED',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}

