import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React from 'react';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import { ThemeProvider } from '@/context/ThemeProvider';
import Navbar from '@/components/navbar/Navbar';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'PROMPTED',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <html lang="en">
      <body className={`${inter.className} h-screen`}>
        <ClerkProvider publishableKey={process.env.CLERK_PUBLISHABLE_KEY} afterSignInUrl="/dashboard"
          afterSignUpUrl="/dashboard">
          <ThemeProvider>
            <div className="relative left-0 top-0 h-screen">

              <Navbar />
              {children}
            </div>
          </ThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}

